name: Publish Release

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run tests
        run: make test

  release:
    needs: test
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check for Bump commit
        id: check_feat
        run: |
          COMMIT_MSG=$(git log -1 --pretty=format:"%s")
          
          if [[ "$COMMIT_MSG" == Bump* ]]; then
            echo "should_release=true" >> $GITHUB_OUTPUT
          else
            echo "should_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate version tag
        if: steps.check_feat.outputs.should_release == 'true'
        id: version
        run: |
          VERSION="v$(date +'%Y.%m.%d-%H%M%S')"
          echo "tag=$VERSION" >> $GITHUB_OUTPUT

      - name: Generate changelog
        if: steps.check_feat.outputs.should_release == 'true'
        id: changelog
        run: |
          # Get the body of the Bump commit
          CHANGELOG=$(git log -1 --pretty=format:"%b")

          if [ -z "$CHANGELOG" ]; then
            CHANGELOG="No changelog provided"
          fi

          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Build/prepare release artifact
        if: steps.check_feat.outputs.should_release == 'true'
        run: make build-workflow

      - name: Create Release
        if: steps.check_feat.outputs.should_release == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: Release ${{ steps.version.outputs.tag }}
          body: ${{ steps.changelog.outputs.changelog }}
          files: |
            GitHub.alfredworkflow
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
